name: ğŸš€ Deploy API (FTP)

on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: ğŸšš Deploy para ${{ github.ref_name }}
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout do cÃ³digo
        uses: actions/checkout@v4

      - name: ğŸ“‚ Sincronizando Ambiente Principal
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.PROD_SERVER }}
          username: ${{ secrets.PROD_USER  }}
          password: ${{ secrets.PROD_PASS }}
          server-dir: ./
          exclude: |
            **
            !app/**
            !resources/**
            !config/**
            !routes/**
            !public/css/**
            !public/js/**
